### ISSUE TITLE
空格选词

### ISSUE THREAD

**Issue by saintnever** [dramforever/flypy-emacs#1]
使用发现选词时，用空格选第一选项会导致多一个空格。
另外，用;选第二选项无法使用，还是挺影响操作的

**Comment by dramforever** [comment]
啊，居然有人关注这个项目，感谢

坏消息：第一个问题我没有发现，第二个问题我也考虑过，不知道怎么解决。。。

不过还是感谢你的支持啦~

**Comment by saintnever** [comment]
这个是我找的到的小鹤在emacs里最方便的解决方案了，感谢！
四键上屏是没问题，但空格这个真的是没法用啊。。是我安装有问题吗？我就是把el文件下下来然后在emacs里load-file 一下，然后用 C-\ 切换的

**Comment by dramforever** [comment]
最新版的应该已经修复了两个问题了
- 我用改码表的方法解决了分号次选，你看看行不
- 空格那个，是我的错，我有个古老的 commit 没上传……

还有问题就继续提吧 :smiley:

**Comment by saintnever** [comment]
完美解决！感谢！
