### ISSUE TITLE
这个是小鹤双拼的包？我该怎么用？

### ISSUE THREAD

**Issue by ghost** [dramforever/flypy-emacs#2]
M-x load-file ..
it doesn't work.

**Comment by dramforever** [comment]
坏消息：我自己都忘了 :facepalm:

#1 的 @saintnever 老哥还记得么……求助

**Comment by saintnever** [comment]
下下来，在init 里 (require 'flypy)，M-x set-input-method 输入chinese-flypy

**Comment by ghost** [comment]
@saintnever Error in dotspacemacs/user-config: Symbol’s value as variable is void: <!DOCTYPE  出先这个错误。

**Comment by ghost** [comment]
@saintnever 我是在 termux 上使用的 spacemacs .

**Comment by ghost** [comment]
@saintnever 抱歉，我在手机上下的，下错了。我说呢。
